### ISSUE TITLE
[Request Fitur] Penyederhanaan proses inisialisasi projek

### ISSUE THREAD

**Issue by 7dp** [react-crocodic/react_native_starter#13]
## Apa masalahnya?
Mengapa kita harus `commit` 2 kali ("initial commit" & "rename app") ?

## Apakah itu hal yang urgent / important / good to do? sebutkan alasannya...
Anda tahu bahwa di sini efisiensi memegang kendali (nada sok keren), tentu penyederhanaan proses adalah pencapaian yang  lebih baik.
## Ungkapkan perbedaan yang dapat diukur antara masalah yang ada sekarang dengan ekspektasi
Coba bayangkan saat Anda membuat projek baru, dengan nama app yang Anda tentukan, lalu bebarapa saat kemudian Anda melakukan commit untuk pertama kali nya. Di titik commit tersebut pasti nama app sudah ter set dengan baik yaitu saat kita meng init projek tadi, sedangkan jika melakukan apa yang ada di section "Apa masalahnya?" di atas, itu tidak seefisien dibandingkan dengan contoh yang saya minta bayangkan di atas.
## Apa saja yang perlu dilakukan untuk mencapai ekspektasi tersebut?
Memangkas proses commit menjadi:
> npx react-native-rename "$1" -b $2;
> node support-files/pod-repo-update.js;
> Di sini lah baru melakukan `initial commit`.

Maturnuwun

**Comment by a-nice-username** [comment]
okey noted @7dp react-native-rename tidak bekerja kalau tidak di initial commit dulu setahu yang saya test, disitu aku workaround initial commit dulu baru rename agar bisa, baru next nya melakukan rename dan commit lagi

**Comment by a-nice-username** [comment]
di sisi lain dengan commit terpisah bisa di revert ke initial sebelum ke rename, mungkin bermanfaat kalau mau pakai settingan bawaan starter

**Comment by a-nice-username** [comment]
itu yang ada dipikiranku sekarang, masih belum tahu yang mana yang lebih baik, thanks cak

**Comment by 7dp** [comment]
Baiklah mas, tak ulik lagi soal komenmu yang pertama

**Comment by 7dp** [comment]
> okey noted @7dp react-native-rename tidak bekerja kalau tidak di initial commit dulu setahu yang saya test, disitu aku workaround initial commit dulu baru rename agar bisa, baru next nya melakukan rename dan commit lagi

Ok, soal ini, sudah saya coba, rn rename tetap bisa rename dengan mulus secara keseluruhan, kecuali bundle id iOS yang mana tidak berubah.
Jika kita memberikan experience inisialisasi projek yang semakin mirip dengan insialisasi dimana kita telah terbiasa menggunakan command seperti ini:

> npx react-native init MyAwesomeApp --template react-native-template-typescript

itu adalah langkah yang lebih baik untuk rekan-rekan yang akan berpeluang besar menggunakan starter ini kedepannya.

Maturnuwun

**Comment by a-nice-username** [comment]
disimpulkan ekpsektasimu ingin commit nya 1 saja? initial commit?

**Comment by a-nice-username** [comment]
> Jika kita memberikan experience inisialisasi projek yang semakin mirip dengan insialisasi dimana kita telah terbiasa menggunakan command seperti ini:
> 
> > npx react-native init MyAwesomeApp --template react-native-template-typescript

ini beda isu lagi, create new issue jika ingin didiskusikan lebih lanjut

**Comment by 7dp** [comment]
> disimpulkan ekpsektasimu ingin commit nya 1 saja? initial commit?

Iya, benar. Walaupun hanya 2 proses yang disederhanakan, itu juga langkah yang lebih baik.

**Comment by nald-dev** [comment]
1. dirasa benefit untuk tetap 2 commit, ada capability untuk revert ke versi starter lewat git 
2. skema clone dengan react native --template belum coba lagi, pertimbangkan untuk semua fiturnya bekerja termasuk setting bundle identifier
