### ISSUE TITLE
Package name di file _BUCK tetap tidak berganti setelah inisialisasi projek

### ISSUE THREAD

**Issue by 7dp** [react-crocodic/react_native_starter#15]
Setelah inisialisasi projek baru dengan perintah yang telah disediakan, saya menemukan package name yang tidak berubah dengan semestinya, seharusnya `id.wisely.bookr` dalam file `_BUCK`.

![image](https://user-images.githubusercontent.com/49138064/112921770-8f653180-9135-11eb-8195-731cdae25fac.png)

Apakah ini bug dari lib rn-rename?

Maturnuwun

**Comment by nald-dev** [comment]
@7dp https://github.com/junedomingo/react-native-rename/issues/127

react native merubah nama file ```BUCK``` di versi 0.5x.y ke ```_BUCK``` di react native 0.6x.y

sedangkan react-native-rename bekerja hanya mengedit file BUCK, dari situ rename tidak bekerja

untuk solusi bisa saya buat workaround dulu dari ```installation.sh```

**Comment by nald-dev** [comment]
fixed in https://github.com/react-crocodic/react_native_starter/commit/b303eecfa05556c44dd59531bdada22028391360

**Comment by 7dp** [comment]
Sip, makasih mas
